export const GET_ACTIVE_BARRELS = "GET_ACTIVE_BARRELS";
export const GET_INACTIVE_BARRELS = "GET_INACTIVE_BARRELS";
export const EDIT_BARREL_SUCCESS = "EDIT_BARREL_SUCCESS";
export const EDIT_BARREL_ERROR = "EDIT_BARREL_ERROR";
export const CREATE_BARREL_SUCCESS = "CREATE_BARREL_SUCCESS";
export const CREATE_BARREL_ERROR = "CREATE_BARREL_ERROR";
export const DELETE_BARREL_SUCCESS = "DELETE_BARREL_SUCCESS";
export const DELETE_BARREL_ERROR = "DELETE_BARREL_ERROR";