export const GET_MEASURMENTS_SUCCESS = "GET_MEASURMENTS_SUCCESS";
export const CREATE_MEASURMENTS_SUCCESS = "CREATE_MEASURMENTS_SUCCESS";
export const CREATE_MEASURMENTS_ERROR = "CREATE_MEASURMENTS_ERROR";